### ISSUE TITLE
simpfand cannot read temperature input

### ISSUE THREAD

**Issue by bjo81** [hspak/simpfand#2]
simpfand[13184]: fan control started
simpfand[13184]: error: could not read temperature input
simpfand[13184]: fan level set to auto, exiting

**Comment by hspak** [comment]
So simpfand right now only looks at two places for temperature readings:

    /sys/devices/platform/coretemp.0/temp1_input
    /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input

I'm guessing the newer models have set these somewhere else. If you could dig in your system and look for a `temp1_input`, I'd be happy to commit or accept a pull request.

**Comment by bjo81** [comment]
My Thinkpad is no new model, it's a X200. But I have only temp2_input and temp3_input. Maybe you could make the input configurable?

ls /sys/devices/platform/coretemp.0/hwmon/hwmon1/
device@  subsystem@        temp2_input  temp3_crit        temp3_label
name     temp2_crit        temp2_label  temp3_crit_alarm  temp3_max
power/   temp2_crit_alarm  temp2_max    temp3_input       uevent

**Comment by hspak** [comment]
f27aa193c5a239b2457d85451a05940c49a226de commit should fix it. I look for 1, 2 and 3 now.

**Comment by bjo81** [comment]
Thanks, works now. Why do you use coretemp and not thinkpad?

**Comment by hspak** [comment]
No real reason other than the fact that I found about it first.
