### ISSUE TITLE
kernel 4.0.4-2: error: could not find temp path

### ISSUE THREAD

**Issue by bjo81** [hspak/simpfand#3]
While using Kernel 4.0.4 on Arch Linux, simpfand doesn't work any more.

**Comment by hspak** [comment]
Gah, they keep changing it up. I really should write up some sort of logic for looking up the appropriate files, but 45f686c6ca55d98f793bd96e52d27f1c923867e2 should be enough.

My main driver is no longer a Thinkpad so I will be reactive instead of proactive with bugs. Thanks for these reports!

**Comment by bjo81** [comment]
Thanks for the fast fix, it works again!

**Comment by hspak** [comment]
No problem :smiley:
